version: '3.8'

services:
  mongo:
    image: arm64v8/mongo:4.4-bionic
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=SUPERSECRETPASSWORD
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./trolley-problem-backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:SUPERSECRETPASSWORD@mongo:27017/trolley-problem?authSource=admin
    secrets:
      - delete_password
    depends_on:
      - mongo

  frontend:
    build: ./trolley-problem-frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

secrets:
  delete_password:
    external: true
    name: delete_votes_password

volumes:
  mongo-data:
