version: '3.8'

services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./trolley-problem-backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/trolley-problem
    depends_on:
      - mongo

  frontend:
    build: ./trolley-problem-frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  mongo-data:
