import type { Metadata } from "next"
import { Inter, Playpen_Sans } from "next/font/google"
import "./globals.css"

const playpen_Sans = Playpen_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playpen-sans",
})

import Wrapper from "./Wrapper"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${playpen_Sans.variable}`}>
        <Wrapper>
          {children}
        </Wrapper>
      </body>
    </html>
  )
}
